version: 1
jobs:
  macOS_swift_5.0:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux_swift_5.0:
    docker:
      - image: norionomura/swift:50
    steps:
      - checkout
      - run: swift build
      - run: swift test
workflows:
  version: 2
  workflow:
    jobs:
      - macOS_swift_5.0
      # Linux disabled for now
      #- linux_swift_5.0
